package com.thru.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.thru.model.NFTModel;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Service
public class NFTService {
    public List<NFTModel> getNftsByOpenseaAPI() {
        RestTemplate restTemplate = new RestTemplate();
        try {
            String url = "https://api.opensea.io/api/v1/assets?owner=0xd1B948b9eB3D433d780b9E699f5494429e4CA51D&limit=10";
            OkHttpClient client = new OkHttpClient();
            Request request = new Request.Builder().url(url).get().addHeader("Accept", "application/json").build();
            Response response = client.newCall(request).execute();

            String response1 = "{"
                    + "    \"next\": null,"
                    + "    \"previous\": null,"
                    + "    \"assets\": ["
                    + "        {"
                    + "            \"id\": 492670226,"
                    + "            \"num_sales\": 0,"
                    + "            \"background_color\": null,"
                    + "            \"image_url\": \"https://lh3.googleusercontent.com/e1gQKlrbwGuZmIakFBAdQO_VEBDWtwudseNg866HlxnZVu6zxfSupLJzBejIx4mwrvrc4kOTHYgruRSdmp-CwbYyyszNIPEIGTidfA\","
                    + "            \"image_preview_url\": \"https://lh3.googleusercontent.com/e1gQKlrbwGuZmIakFBAdQO_VEBDWtwudseNg866HlxnZVu6zxfSupLJzBejIx4mwrvrc4kOTHYgruRSdmp-CwbYyyszNIPEIGTidfA=s250\","
                    + "            \"image_thumbnail_url\": \"https://lh3.googleusercontent.com/e1gQKlrbwGuZmIakFBAdQO_VEBDWtwudseNg866HlxnZVu6zxfSupLJzBejIx4mwrvrc4kOTHYgruRSdmp-CwbYyyszNIPEIGTidfA=s128\","
                    + "            \"image_original_url\": \"https://opensea.mypinata.cloud/ipfs/QmY77ewzEa3gt3p7267tBeeUJZfKoqEoFdxECbgAQMJWRN\","
                    + "            \"animation_url\": null,"
                    + "            \"animation_original_url\": null,"
                    + "            \"name\": \"PRD_X #778\","
                    + "            \"description\": \"A collection of 8888 Hyper-intelligent A.I clones of PRD_X composed of unique & lifelike 3D traits. Each clone embody a wide array of eclectic qualities and vibes which gives them each their own bespoke fusion of ideas, style & identity. Each PRD_X clone unlocks the gate to SMATh World and additional benefits developed by Team SMATh. #Webuilddifferent\","
                    + "            \"external_link\": \"https://www.smath.world\","
                    + "            \"asset_contract\": {"
                    + "                \"address\": \"0x636b21137054e5756cb9ea2f59ca876d6b1446a1\","
                    + "                \"asset_contract_type\": \"non-fungible\","
                    + "                \"created_date\": \"2022-06-16T05:25:24.410905\","
                    + "                \"name\": \"SMATh World - PRD_X\","
                    + "                \"nft_version\": null,"
                    + "                \"opensea_version\": null,"
                    + "                \"owner\": 445473919,"
                    + "                \"schema_name\": \"ERC721\","
                    + "                \"symbol\": \"PRDX\","
                    + "                \"total_supply\": null,"
                    + "                \"description\": \"A collection of 4509 Hyper-intelligent A.I clones of PRD_X composed of unique & lifelike 3D traits. Each clone embody a wide array of eclectic qualities and vibes which gives them each their own bespoke fusion of ideas, style & identity. Each PRD_X clone unlocks the gate to SMATh World and additional benefits developed by Team SMATh. #Webuilddifferent \","
                    + "                \"external_link\": \"https://smath.world/\","
                    + "                \"image_url\": \"https://openseauserdata.com/files/637e9974ee18fb37c4a144e25a499633.png\","
                    + "                \"default_to_fiat\": false,"
                    + "                \"dev_buyer_fee_basis_points\": 0,"
                    + "                \"dev_seller_fee_basis_points\": 750,"
                    + "                \"only_proxied_transfers\": false,"
                    + "                \"opensea_buyer_fee_basis_points\": 0,"
                    + "                \"opensea_seller_fee_basis_points\": 250,"
                    + "                \"buyer_fee_basis_points\": 0,"
                    + "                \"seller_fee_basis_points\": 1000,"
                    + "                \"payout_address\": \"0x70fc844ea1d1cf6eeef818584d5ed3b9eca0b5a4\""
                    + "            },"
                    + "            \"permalink\": \"https://opensea.io/assets/ethereum/0x636b21137054e5756cb9ea2f59ca876d6b1446a1/778\","
                    + "            \"collection\": {"
                    + "                \"banner_image_url\": \"https://openseauserdata.com/files/21a8f853b29e5959bd8861f079641aec.jpg\","
                    + "                \"chat_url\": null,"
                    + "                \"created_date\": \"2022-06-16T05:57:32.948808\","
                    + "                \"default_to_fiat\": false,"
                    + "                \"description\": \"A collection of 4509 Hyper-intelligent A.I clones of PRD_X composed of unique & lifelike 3D traits. Each clone embody a wide array of eclectic qualities and vibes which gives them each their own bespoke fusion of ideas, style & identity. Each PRD_X clone unlocks the gate to SMATh World and additional benefits developed by Team SMATh. #Webuilddifferent \","
                    + "                \"dev_buyer_fee_basis_points\": \"0\","
                    + "                \"dev_seller_fee_basis_points\": \"750\","
                    + "                \"discord_url\": \"https://discord.gg/smathworld\","
                    + "                \"display_data\": {"
                    + "                    \"card_display_style\": \"cover\""
                    + "                },"
                    + "                \"external_url\": \"https://smath.world/\","
                    + "                \"featured\": false,"
                    + "                \"featured_image_url\": \"https://openseauserdata.com/files/21a8f853b29e5959bd8861f079641aec.jpg\","
                    + "                \"hidden\": false,"
                    + "                \"safelist_request_status\": \"not_requested\","
                    + "                \"image_url\": \"https://openseauserdata.com/files/637e9974ee18fb37c4a144e25a499633.png\","
                    + "                \"is_subject_to_whitelist\": false,"
                    + "                \"large_image_url\": \"https://openseauserdata.com/files/21a8f853b29e5959bd8861f079641aec.jpg\","
                    + "                \"medium_username\": null,"
                    + "                \"name\": \"SMATh World - PRD_X\","
                    + "                \"only_proxied_transfers\": false,"
                    + "                \"opensea_buyer_fee_basis_points\": \"0\","
                    + "                \"opensea_seller_fee_basis_points\": \"250\","
                    + "                \"payout_address\": \"0x70fc844ea1d1cf6eeef818584d5ed3b9eca0b5a4\","
                    + "                \"require_email\": false,"
                    + "                \"short_description\": null,"
                    + "                \"slug\": \"smathworld-prdx\","
                    + "                \"telegram_url\": null,"
                    + "                \"twitter_username\": \"TeamSMATh\","
                    + "                \"instagram_username\": \"SMATh_world\","
                    + "                \"wiki_url\": null,"
                    + "                \"is_nsfw\": false"
                    + "            },"
                    + "            \"decimals\": null,"
                    + "            \"token_metadata\": \"https://opensea.mypinata.cloud/ipfs/QmTcDuiL8QxDwEvpJfbhahtktohnKUmMPpaLM1tKWYKMdw/778\","
                    + "            \"is_nsfw\": false,"
                    + "            \"owner\": {"
                    + "                \"user\": {"
                    + "                    \"username\": \"JaydenTinto\""
                    + "                },"
                    + "                \"profile_img_url\": \"https://storage.googleapis.com/opensea-static/opensea-profile/27.png\","
                    + "                \"address\": \"0xd1b948b9eb3d433d780b9e699f5494429e4ca51d\","
                    + "                \"config\": \"\""
                    + "            },"
                    + "            \"sell_orders\": null,"
                    + "            \"seaport_sell_orders\": null,"
                    + "            \"creator\": {"
                    + "                \"user\": {"
                    + "                    \"username\": \"smath_dev\""
                    + "                },"
                    + "                \"profile_img_url\": \"https://storage.googleapis.com/opensea-static/opensea-profile/27.png\","
                    + "                \"address\": \"0x7770ccc4f31b0068ba4885ec9272dfcbfc8f57fd\","
                    + "                \"config\": \"\""
                    + "            },"
                    + "            \"traits\": [],"
                    + "            \"last_sale\": null,"
                    + "            \"top_bid\": null,"
                    + "            \"listing_date\": null,"
                    + "            \"is_presale\": false,"
                    + "            \"transfer_fee_payment_token\": null,"
                    + "            \"transfer_fee\": null,"
                    + "            \"token_id\": \"778\""
                    + "        },"
                    + "        {"
                    + "            \"id\": 492670216,"
                    + "            \"num_sales\": 0,"
                    + "            \"background_color\": null,"
                    + "            \"image_url\": \"https://lh3.googleusercontent.com/e1gQKlrbwGuZmIakFBAdQO_VEBDWtwudseNg866HlxnZVu6zxfSupLJzBejIx4mwrvrc4kOTHYgruRSdmp-CwbYyyszNIPEIGTidfA\","
                    + "            \"image_preview_url\": \"https://lh3.googleusercontent.com/e1gQKlrbwGuZmIakFBAdQO_VEBDWtwudseNg866HlxnZVu6zxfSupLJzBejIx4mwrvrc4kOTHYgruRSdmp-CwbYyyszNIPEIGTidfA=s250\","
                    + "            \"image_thumbnail_url\": \"https://lh3.googleusercontent.com/e1gQKlrbwGuZmIakFBAdQO_VEBDWtwudseNg866HlxnZVu6zxfSupLJzBejIx4mwrvrc4kOTHYgruRSdmp-CwbYyyszNIPEIGTidfA=s128\","
                    + "            \"image_original_url\": \"https://opensea.mypinata.cloud/ipfs/QmY77ewzEa3gt3p7267tBeeUJZfKoqEoFdxECbgAQMJWRN\","
                    + "            \"animation_url\": null,"
                    + "            \"animation_original_url\": null,"
                    + "            \"name\": \"PRD_X #777\","
                    + "            \"description\": \"A collection of 8888 Hyper-intelligent A.I clones of PRD_X composed of unique & lifelike 3D traits. Each clone embody a wide array of eclectic qualities and vibes which gives them each their own bespoke fusion of ideas, style & identity. Each PRD_X clone unlocks the gate to SMATh World and additional benefits developed by Team SMATh. #Webuilddifferent\","
                    + "            \"external_link\": \"https://www.smath.world\","
                    + "            \"asset_contract\": {"
                    + "                \"address\": \"0x636b21137054e5756cb9ea2f59ca876d6b1446a1\","
                    + "                \"asset_contract_type\": \"non-fungible\","
                    + "                \"created_date\": \"2022-06-16T05:25:24.410905\","
                    + "                \"name\": \"SMATh World - PRD_X\","
                    + "                \"nft_version\": null,"
                    + "                \"opensea_version\": null,"
                    + "                \"owner\": 445473919,"
                    + "                \"schema_name\": \"ERC721\","
                    + "                \"symbol\": \"PRDX\","
                    + "                \"total_supply\": null,"
                    + "                \"description\": \"A collection of 4509 Hyper-intelligent A.I clones of PRD_X composed of unique & lifelike 3D traits. Each clone embody a wide array of eclectic qualities and vibes which gives them each their own bespoke fusion of ideas, style & identity. Each PRD_X clone unlocks the gate to SMATh World and additional benefits developed by Team SMATh. #Webuilddifferent \","
                    + "                \"external_link\": \"https://smath.world/\","
                    + "                \"image_url\": \"https://openseauserdata.com/files/637e9974ee18fb37c4a144e25a499633.png\","
                    + "                \"default_to_fiat\": false,"
                    + "                \"dev_buyer_fee_basis_points\": 0,"
                    + "                \"dev_seller_fee_basis_points\": 750,"
                    + "                \"only_proxied_transfers\": false,"
                    + "                \"opensea_buyer_fee_basis_points\": 0,"
                    + "                \"opensea_seller_fee_basis_points\": 250,"
                    + "                \"buyer_fee_basis_points\": 0,"
                    + "                \"seller_fee_basis_points\": 1000,"
                    + "                \"payout_address\": \"0x70fc844ea1d1cf6eeef818584d5ed3b9eca0b5a4\""
                    + "            },"
                    + "            \"permalink\": \"https://opensea.io/assets/ethereum/0x636b21137054e5756cb9ea2f59ca876d6b1446a1/777\","
                    + "            \"collection\": {"
                    + "                \"banner_image_url\": \"https://openseauserdata.com/files/21a8f853b29e5959bd8861f079641aec.jpg\","
                    + "                \"chat_url\": null,"
                    + "                \"created_date\": \"2022-06-16T05:57:32.948808\","
                    + "                \"default_to_fiat\": false,"
                    + "                \"description\": \"A collection of 4509 Hyper-intelligent A.I clones of PRD_X composed of unique & lifelike 3D traits. Each clone embody a wide array of eclectic qualities and vibes which gives them each their own bespoke fusion of ideas, style & identity. Each PRD_X clone unlocks the gate to SMATh World and additional benefits developed by Team SMATh. #Webuilddifferent \","
                    + "                \"dev_buyer_fee_basis_points\": \"0\","
                    + "                \"dev_seller_fee_basis_points\": \"750\","
                    + "                \"discord_url\": \"https://discord.gg/smathworld\","
                    + "                \"display_data\": {"
                    + "                    \"card_display_style\": \"cover\""
                    + "                },"
                    + "                \"external_url\": \"https://smath.world/\","
                    + "                \"featured\": false,"
                    + "                \"featured_image_url\": \"https://openseauserdata.com/files/21a8f853b29e5959bd8861f079641aec.jpg\","
                    + "                \"hidden\": false,"
                    + "                \"safelist_request_status\": \"not_requested\","
                    + "                \"image_url\": \"https://openseauserdata.com/files/637e9974ee18fb37c4a144e25a499633.png\","
                    + "                \"is_subject_to_whitelist\": false,"
                    + "                \"large_image_url\": \"https://openseauserdata.com/files/21a8f853b29e5959bd8861f079641aec.jpg\","
                    + "                \"medium_username\": null,"
                    + "                \"name\": \"SMATh World - PRD_X\","
                    + "                \"only_proxied_transfers\": false,"
                    + "                \"opensea_buyer_fee_basis_points\": \"0\","
                    + "                \"opensea_seller_fee_basis_points\": \"250\","
                    + "                \"payout_address\": \"0x70fc844ea1d1cf6eeef818584d5ed3b9eca0b5a4\","
                    + "                \"require_email\": false,"
                    + "                \"short_description\": null,"
                    + "                \"slug\": \"smathworld-prdx\","
                    + "                \"telegram_url\": null,"
                    + "                \"twitter_username\": \"TeamSMATh\","
                    + "                \"instagram_username\": \"SMATh_world\","
                    + "                \"wiki_url\": null,"
                    + "                \"is_nsfw\": false"
                    + "            },"
                    + "            \"decimals\": null,"
                    + "            \"token_metadata\": \"https://opensea.mypinata.cloud/ipfs/QmTcDuiL8QxDwEvpJfbhahtktohnKUmMPpaLM1tKWYKMdw/777\","
                    + "            \"is_nsfw\": false,"
                    + "            \"owner\": {"
                    + "                \"user\": {"
                    + "                    \"username\": \"JaydenTinto\""
                    + "                },"
                    + "                \"profile_img_url\": \"https://storage.googleapis.com/opensea-static/opensea-profile/27.png\","
                    + "                \"address\": \"0xd1b948b9eb3d433d780b9e699f5494429e4ca51d\","
                    + "                \"config\": \"\""
                    + "            },"
                    + "            \"sell_orders\": null,"
                    + "            \"seaport_sell_orders\": null,"
                    + "            \"creator\": {"
                    + "                \"user\": {"
                    + "                    \"username\": \"smath_dev\""
                    + "                },"
                    + "                \"profile_img_url\": \"https://storage.googleapis.com/opensea-static/opensea-profile/27.png\","
                    + "                \"address\": \"0x7770ccc4f31b0068ba4885ec9272dfcbfc8f57fd\","
                    + "                \"config\": \"\""
                    + "            },"
                    + "            \"traits\": [],"
                    + "            \"last_sale\": null,"
                    + "            \"top_bid\": null,"
                    + "            \"listing_date\": null,"
                    + "            \"is_presale\": false,"
                    + "            \"transfer_fee_payment_token\": null,"
                    + "            \"transfer_fee\": null,"
                    + "            \"token_id\": \"777\""
                    + "        },"
                    + "        {"
                    + "            \"id\": 212756683,"
                    + "            \"num_sales\": 1,"
                    + "            \"background_color\": null,"
                    + "            \"image_url\": \"https://lh3.googleusercontent.com/6LQ7_sp1--nwGYYcW5D3dmE1hdRuysb59oz0aTXSDDhivQAjeVFhyrV5uknawUy1dhvK2W7NedDdaZyF6Y_9FGE1zHhE3mbbu6VWZg\","
                    + "            \"image_preview_url\": \"https://lh3.googleusercontent.com/6LQ7_sp1--nwGYYcW5D3dmE1hdRuysb59oz0aTXSDDhivQAjeVFhyrV5uknawUy1dhvK2W7NedDdaZyF6Y_9FGE1zHhE3mbbu6VWZg=s250\","
                    + "            \"image_thumbnail_url\": \"https://lh3.googleusercontent.com/6LQ7_sp1--nwGYYcW5D3dmE1hdRuysb59oz0aTXSDDhivQAjeVFhyrV5uknawUy1dhvK2W7NedDdaZyF6Y_9FGE1zHhE3mbbu6VWZg=s128\","
                    + "            \"image_original_url\": \"https://catbotica.mypinata.cloud/ipfs/QmSzmvzdd5KV6qd3o9CJVFk5zsxtYXr8aXWh4CRzAWuTmf/1938.jpg\","
                    + "            \"animation_url\": null,"
                    + "            \"animation_original_url\": null,"
                    + "            \"name\": \"Catbotica #1938\","
                    + "            \"description\": \"CATBOTICA is a hand-drawn, generative pfp project consisting of 12,000 2D assets called Catbots on the Ethereum blockchain as ERC-721 standard non-fungible tokens (NFTs). These 2D NFTs will grant access to special channels in the Discord, qualify the holder for various NFT airdrops, and unlock additional NFT minting capabilities which will have future utility in the proposed roadmap.\","
                    + "            \"external_link\": \"https://catbotica.com\","
                    + "            \"asset_contract\": {"
                    + "                \"address\": \"0x25e5e2b4b8f11c32cdd48c2fb394fbda9a2861f7\","
                    + "                \"asset_contract_type\": \"non-fungible\","
                    + "                \"created_date\": \"2022-01-14T22:45:00.334491\","
                    + "                \"name\": \"Catbotica\","
                    + "                \"nft_version\": \"3.0\","
                    + "                \"opensea_version\": null,"
                    + "                \"owner\": 199534958,"
                    + "                \"schema_name\": \"ERC721\","
                    + "                \"symbol\": \"CBOT\","
                    + "                \"total_supply\": \"0\","
                    + "                \"description\": \"CATBOTICA is a hand-drawn, generative pfp project consisting of 12,000 2D assets called Catbots on the Ethereum blockchain as ERC-721 standard non-fungible tokens (NFTs). These 2D NFTs will grant access to special channels in the Discord, qualify the holder for various NFT airdrops, and unlock additional NFT minting capabilities which will have future utility in the proposed roadmap.\","
                    + "                \"external_link\": \"https://catbotica.com\","
                    + "                \"image_url\": \"https://lh3.googleusercontent.com/TR7Q-foriSZqKkvc3-BMYUL_3lqupD2mD4GZ1G-5W_zxHK1fyjUnknPObQVBznrNbW8ICWc6aiMnByFFFiEFNdXk0egYri0o7xed4NA=s120\","
                    + "                \"default_to_fiat\": false,"
                    + "                \"dev_buyer_fee_basis_points\": 0,"
                    + "                \"dev_seller_fee_basis_points\": 750,"
                    + "                \"only_proxied_transfers\": false,"
                    + "                \"opensea_buyer_fee_basis_points\": 0,"
                    + "                \"opensea_seller_fee_basis_points\": 250,"
                    + "                \"buyer_fee_basis_points\": 0,"
                    + "                \"seller_fee_basis_points\": 1000,"
                    + "                \"payout_address\": \"0x241c9246a21886f9465362ad4888d51d955b7aaa\""
                    + "            },"
                    + "            \"permalink\": \"https://opensea.io/assets/ethereum/0x25e5e2b4b8f11c32cdd48c2fb394fbda9a2861f7/1938\","
                    + "            \"collection\": {"
                    + "                \"banner_image_url\": \"https://lh3.googleusercontent.com/YyI5oK0G49XrE3L-3E_h1zcEW3LOtHZrNoi1cov-20_4ZiEoNmNZX9BAy51INE6PXxACj5NOq1fxRauEeGYPtiSCTM07FzGbm_gw=s2500\","
                    + "                \"chat_url\": null,"
                    + "                \"created_date\": \"2022-01-14T23:49:14.026638\","
                    + "                \"default_to_fiat\": false,"
                    + "                \"description\": \"CATBOTICA is a hand-drawn, generative pfp project consisting of 12,000 2D assets called Catbots on the Ethereum blockchain as ERC-721 standard non-fungible tokens (NFTs). These 2D NFTs will grant access to special channels in the Discord, qualify the holder for various NFT airdrops, and unlock additional NFT minting capabilities which will have future utility in the proposed roadmap.\","
                    + "                \"dev_buyer_fee_basis_points\": \"0\","
                    + "                \"dev_seller_fee_basis_points\": \"750\","
                    + "                \"discord_url\": \"https://discord.gg/catbotica\","
                    + "                \"display_data\": {"
                    + "                    \"card_display_style\": \"cover\""
                    + "                },"
                    + "                \"external_url\": \"https://catbotica.com\","
                    + "                \"featured\": false,"
                    + "                \"featured_image_url\": \"https://lh3.googleusercontent.com/V2LKzRdArJb_DPF-HB-l_VAszTCaDVQf7_-c7F2CjhFJAW3XhjUFfVrfDIsfiDXCnUuW4oeWl6CFeMoqv_zhcW1kQF_2d2tQDiKr2Q=s300\","
                    + "                \"hidden\": false,"
                    + "                \"safelist_request_status\": \"approved\","
                    + "                \"image_url\": \"https://lh3.googleusercontent.com/TR7Q-foriSZqKkvc3-BMYUL_3lqupD2mD4GZ1G-5W_zxHK1fyjUnknPObQVBznrNbW8ICWc6aiMnByFFFiEFNdXk0egYri0o7xed4NA=s120\","
                    + "                \"is_subject_to_whitelist\": false,"
                    + "                \"large_image_url\": \"https://lh3.googleusercontent.com/V2LKzRdArJb_DPF-HB-l_VAszTCaDVQf7_-c7F2CjhFJAW3XhjUFfVrfDIsfiDXCnUuW4oeWl6CFeMoqv_zhcW1kQF_2d2tQDiKr2Q=s300\","
                    + "                \"medium_username\": null,"
                    + "                \"name\": \"CATBOTICA\","
                    + "                \"only_proxied_transfers\": false,"
                    + "                \"opensea_buyer_fee_basis_points\": \"0\","
                    + "                \"opensea_seller_fee_basis_points\": \"250\","
                    + "                \"payout_address\": \"0x241c9246a21886f9465362ad4888d51d955b7aaa\","
                    + "                \"require_email\": false,"
                    + "                \"short_description\": null,"
                    + "                \"slug\": \"catbotica\","
                    + "                \"telegram_url\": null,"
                    + "                \"twitter_username\": \"CATBOTICA\","
                    + "                \"instagram_username\": null,"
                    + "                \"wiki_url\": null,"
                    + "                \"is_nsfw\": false"
                    + "            },"
                    + "            \"decimals\": 0,"
                    + "            \"token_metadata\": \"https://catbotica.mypinata.cloud/ipfs/QmYKbREYcDdB17TosqWn7XLJxJA5MytPvhY4gtJRxqFPvW/1938.json\","
                    + "            \"is_nsfw\": false,"
                    + "            \"owner\": {"
                    + "                \"user\": {"
                    + "                    \"username\": \"JaydenTinto\""
                    + "                },"
                    + "                \"profile_img_url\": \"https://storage.googleapis.com/opensea-static/opensea-profile/27.png\","
                    + "                \"address\": \"0xd1b948b9eb3d433d780b9e699f5494429e4ca51d\","
                    + "                \"config\": \"\""
                    + "            },"
                    + "            \"sell_orders\": null,"
                    + "            \"seaport_sell_orders\": null,"
                    + "            \"creator\": {"
                    + "                \"user\": {"
                    + "                    \"username\": \"CATBOTICA\""
                    + "                },"
                    + "                \"profile_img_url\": \"https://storage.googleapis.com/opensea-static/opensea-profile/1.png\","
                    + "                \"address\": \"0x080af67982078ec482cc359a27ef00dbfeed8378\","
                    + "                \"config\": \"\""
                    + "            },"
                    + "            \"traits\": ["
                    + "                {"
                    + "                    \"trait_type\": \"TAIL\","
                    + "                    \"value\": \"Short\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 1251,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"EYES\","
                    + "                    \"value\": \"Default Half\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 437,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"HEADGEAR\","
                    + "                    \"value\": \"Hat Camo Tan\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 200,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"WHISKERS\","
                    + "                    \"value\": \"Neon Teal\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 712,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"LEGS\","
                    + "                    \"value\": \"Shoes Grey\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 202,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"BACK ATTACHMENT\","
                    + "                    \"value\": \"Plug\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 849,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"BACK\","
                    + "                    \"value\": \"Back\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 12000,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"RIGHT SHOULDER\","
                    + "                    \"value\": \"Default\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 12000,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"RIGHT PAW\","
                    + "                    \"value\": \"Default\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 8837,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"TORSO\","
                    + "                    \"value\": \"Default\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 10932,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"LEFT SHOULDER\","
                    + "                    \"value\": \"Default\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 12000,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"HEAD\","
                    + "                    \"value\": \"Default\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 12000,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"LEFT PAW\","
                    + "                    \"value\": \"Chainsaw\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 574,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"CLOTHING\","
                    + "                    \"value\": \"T-Shirt Strawberry\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 264,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"EARS\","
                    + "                    \"value\": \"Stumpy\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 5524,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"BASE\","
                    + "                    \"value\": \"Platinum Faded\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 734,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"ACCESSORY\","
                    + "                    \"value\": \"Monk Necklace\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 646,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"HANDHELD\","
                    + "                    \"value\": \"Microphone\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 582,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"MUZZLE\","
                    + "                    \"value\": \"Jaws\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 520,"
                    + "                    \"order\": null"
                    + "                },"
                    + "                {"
                    + "                    \"trait_type\": \"BACKGROUND\","
                    + "                    \"value\": \"Gradient 11\","
                    + "                    \"display_type\": null,"
                    + "                    \"max_value\": null,"
                    + "                    \"trait_count\": 519,"
                    + "                    \"order\": null"
                    + "                }"
                    + "            ],"
                    + "            \"last_sale\": {"
                    + "                \"asset\": {"
                    + "                    \"decimals\": 0,"
                    + "                    \"token_id\": \"1938\""
                    + "                },"
                    + "                \"asset_bundle\": null,"
                    + "                \"event_type\": \"successful\","
                    + "                \"event_timestamp\": \"2022-06-17T02:21:41\","
                    + "                \"auction_type\": null,"
                    + "                \"total_price\": \"60000000000000000\","
                    + "                \"payment_token\": {"
                    + "                    \"symbol\": \"ETH\","
                    + "                    \"address\": \"0x0000000000000000000000000000000000000000\","
                    + "                    \"image_url\": \"https://openseauserdata.com/files/6f8e2979d428180222796ff4a33ab929.svg\","
                    + "                    \"name\": \"Ether\","
                    + "                    \"decimals\": 18,"
                    + "                    \"eth_price\": \"1.000000000000000\","
                    + "                    \"usd_price\": \"1097.799999999999955000\""
                    + "                },"
                    + "                \"transaction\": null,"
                    + "                \"created_date\": \"2022-06-17T02:22:41.661343\","
                    + "                \"quantity\": \"1\""
                    + "            },"
                    + "            \"top_bid\": null,"
                    + "            \"listing_date\": null,"
                    + "            \"is_presale\": false,"
                    + "            \"transfer_fee_payment_token\": null,"
                    + "            \"transfer_fee\": null,"
                    + "            \"token_id\": \"1938\""
                    + "        }"
                    + "    ]"
                    + "}";



            ObjectMapper mapper = new ObjectMapper();
            Map<String, Object> map = mapper.readValue(response1, Map.class);

            List<Map<String, Object>> nftInfo = (ArrayList<Map<String, Object>>) map.get("assets");

            List<NFTModel> nftList = new ArrayList<>();

            for (Map<String, Object> item : nftInfo) {
                NFTModel nftModel = new NFTModel();
                nftModel.setName((String) item.get("name"));
                nftModel.setTokenId((String) item.get("token_id"));
                nftModel.setOriginUrl((String) item.get("image_original_url"));
                nftModel.setDescription((String) item.get("description"));

                Map<String, Object> contractItem = (Map<String, Object>) item.get("asset_contract");
                nftModel.setContract((String) contractItem.get("address"));

                Map<String, Object> ownerItem = (Map<String, Object>) item.get("owner");
                nftModel.setOwnerAddress((String) ownerItem.get("address"));

                nftList.add(nftModel);
            }

            return nftList;

        } catch (Exception e) {
            e.printStackTrace();
        }

        return null;
    }
}
